config/routes.rb
Rails.application.routes.draw do

  get 'comments/show'

  devise_for :users
  resources :users, only: [:update, :show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  scope :publicly_viewable, -> { where(public: true) }
  scope :privately_viewable, -> { where(public: false) }
  scope :visible_to, -> (user) {user ? all : publicly_viewable}

end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    # @comments = @post.comments.all
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post

    if @post.save_with_initial_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was am error saving the post. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post

    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
        flash[:error] = "There was an error saving the post. Please try again."
        render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post  = Post.find(params[:id])
    title  = @post.title

    authorize @post

    if @post.destroy
      flash[:notice] = "Post '#{title}' was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "Error deleting the post. Please try again."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 5)
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def show
    @topic = Topic.find(params[:id])
    authorize @topic
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 5)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name

    authorize @topic
    if @topic.destroy
      flash[:notice] = "Topic '#{name}' was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "Error deleting topic. Please try again."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.haml
%h1 Edit Topic

.row
  .col-md-4
    %p Guidelines for topics:
    %ul
      %li Make sure the topic is appropriate.
      %li Never insult dogs.
      %li Smile when you type.

  .col-md-8
    = form_for @topic do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', placeholder: "Enter topic name"
      .form-group
        = f.label :description
        = f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description"
      .form-group
        = f.label :public, class: 'checkbox' do
          = f.check_box :public
          Public topic
      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/topics/index.html.haml
%h1 Topics
.row
  .col-md-8
    - @topics.each do |topic|
      .media
        .media-body
          %h4.media-heading
            = link_to markdown(topic.name), topic
            %span.label.label-primary
              = topic.posts.count.to_s
              post(s)
          %small= markdown(topic.description)
    = will_paginate @topics
  .col-md-4
    - if policy(Topic.new).create?
      = link_to "New Topic", new_topic_path, class: 'btn btn-success'

app/views/topics/new.html.haml
%h1 New Topic
.row
  .col-md-4
    %p Guidelines for topics:
    %ul
      %li Make sure the topic is appropriate.
      %li Never insult dogs.
      %li Smile when you type.

  .col-md-8
    = form_for @topic do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', placeholder: "Enter topic name"
      .form-group
        = f.label :description
        = f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description"
      .form-group
        = f.label :public, class: 'checkbox' do
          = f.check_box :public
          Public topic
      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/topics/show.html.haml
.row
  .col-md-12
    %h1= markdown(@topic.name)
.row
  .col-md-8
    %ol.breadcrumb
      %li= link_to 'Home', root_path
      %li= link_to 'Topics', topics_path
      %li.active= @topic.name
  .col-md-2
    - if policy(@topic).update?
      = link_to "Edit Topic", edit_topic_path, class: 'btn btn-success'
  .col-md-2
    - if policy(@topic).destroy?
      = link_to "Delete Topic", @topic ,method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this  topic?'}
.row
  .col-md-12
    %p{:class => "lead"}= @topic.description

.row.topic-posts
  .col-md-10
    = render partial: 'posts/post', collection: @posts
    = will_paginate @posts
  .col-md-2
    - if policy(Post.new).create?
      = link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success'