config/routes.rb
Rails.application.routes.draw do

  get 'comments/show'

  devise_for :users
  resources :users, only: [:update, :show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  mount_uploader :image, ImageUploader

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
    new_rank = points + age

    update_attribute(:rank, new_rank)
  end

  def create_vote
    user.votes.create(value: 1, post: self)
  end

  def save_with_initial_vote
    ActiveRecord::Base.transaction do
      self.create_vote
    end
  end

  # not being used at the moment, instead markdown() method in application_helper is used to conver text to markdown
  def markdown_title
    render_as_markdown(title)
  end

  def markdown_body
    render_as_markdown(body)
  end

  private

  def render_as_markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extentions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extentions)
    (redcarpet.render text).html_safe
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  scope :publicly_viewable, -> { where(public: true) }
  scope :privately_viewable, -> { where(public: false) }
  scope :visible_to, -> (user) {user ? all : publicly_viewable}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    # @comments = @post.comments.all
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post

    if @post.save_with_initial_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was am error saving the post. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post

    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
        flash[:error] = "There was an error saving the post. Please try again."
        render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post  = Post.find(params[:id])
    title  = @post.title

    authorize @post

    if @post.destroy
      flash[:notice] = "Post '#{title}' was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "Error deleting the post. Please try again."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 5)
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def show
    @topic = Topic.find(params[:id])
    authorize @topic
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 5)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name

    authorize @topic
    if @topic.destroy
      flash[:notice] = "Topic '#{name}' was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "Error deleting topic. Please try again."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/posts/_form.html.haml
= form_for [topic, post] do |f|
  - if post.errors.any?
    .alert.alert-danger
      %h4 There are #{pluralize(post.errors.count, "error")}.
      %ul
        - post.errors.full_messages.each do |msg|
          %li= msg
  -# = form_group_tag(post.errors[:title]) do
  .form-group{ :class => (error_class(post.errors[:title])) }
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: "Enter post title"
  -# = form_group_tag(post.errors[:body]) do
  .form-group{ :class => (error_class(post.errors[:body])) }
    = f.label :body
    = f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body"
  - if post.image?
    .form-group
      %p This post image
      = image_tag( post.image.url )
  .form-group
    = f.label :image
    = f.file_field :image
    = f.hidden_field :image_cache
  .form-group
    = f.submit "Save", class: 'btn btn-success'

app/views/topics/posts/edit.html.haml
%h1 Edit Post
.row
  .col-md-4
    %p Guidelines for posts
    %ul
      %li>Make sure the it rhymes.
      %li>Don't use the letter "A".
      %li>The incessant use of hashtags will get you banned.
  .col-md-8
    = render partial: 'form', locals: { topic: @topic, post: @post }

app/views/topics/posts/new.html.haml
%h1 New Post
.row
  .col-md-4
    %p Guidelines for posts
    %ul
      %li>Make sure it rhymes.
      %li>Don't use the letter "A".
      %li>The incessant use of hashtags will get you banned.
  .col-md-8
    = render partial: 'form', locals: { topic: @topic, post: @post }

app/views/topics/posts/show.html.haml
.row
  .col-md-12
    = render partial: 'votes/voter', locals: { post: @post }
    %h1= markdown(@post.title)
    %ol.breadcrumb
      %li= link_to 'Home', root_path
      %li= link_to 'Topics', topics_path
      %li= link_to @post.topic.name, topic_path(@post.topic)
      %li.active= @post.title
.row
  .col-md-12
    %h3= pluralize(@post.points, 'point')
    %small
      = pluralize(@post.up_votes, 'up vote')
      = pluralize(@post.down_votes, 'down vote')
    = render partial: 'favorites/favorite', locals: {post: @post}
.row
  .col-md-8
    %small
      = image_tag(@post.user.avatar.tiny.url) if @post.user.avatar?
      submitted #{time_ago_in_words(@post.created_at)} ago by #{@post.user.name}
    = image_tag(@post.image.url, class: 'thumbnail') if @post.image?
    %p= markdown(@post.body)
    .new-comment
      - if current_user
        - @comment ||= Comment.new
        = render partial: 'comments/form', locals: { post: @post, comment: @comment }
    %h3.js-post-comments-count
      = pluralize(@post.comments.count, 'comment')
    %hr
    .js-comments
      = render partial: 'comments/comment', collection: @post.comments

  .col-md-2
    - if policy(@post).edit?
      = link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success'
  .col-md-2
    - if policy(@post).destroy?
      = link_to "Delete Post", [@topic, @post] ,method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'}